pipeline {
    agent any
    stages {
        stage('Run Docker') {
            steps {
                bat 'docker run -v "C:/ProgramData/Jenkins/.jenkins/workspace:/workspace" my-image echo Hello from container'
            }
        }
    }
}
